tradeshows:
  - name: MWC Barcelona
    url: https://www.mwcbarcelona.com/exhibitors
    selector: "h3 span.ais-Highlight-nonHighlighted"
    dynamic: true
  - name: IFA Berlin
    url: https://b2b.ifa-berlin.com/exhibitors
    selector: "div.exhibitor-card-wrapper h2"
  - name: NRF Big Show
    url: https://nrfbigshow.nrf.com/exhibitors
    selector: "div h5"

amazon:
  base_search_url: https://www.amazon.com/s?k=
database:
  dialect: sqlite
  filename: data/brands.db
